const express = require('express');
const router = express.Router();
const BackEndController = require('./../Controllers/BackEndController');
const cheakLogin = require('../Middlewares/cheakLogin');

router.get('/home',BackEndController.getHome);
router.post('/room1/:id', BackEndController.getRoom1);
router.get('/room', BackEndController.getRoom);
router.get('/checkout', BackEndController.getCheakout);
router.get('/payment/:id', BackEndController.getPayment);
router.post('/payment/:id', BackEndController.postPayment);
//router.post('transection/:id', BackEndController.postTransection);
router.post('/form/:id', BackEndController.getForm);
router.get('/gallary',BackEndController.getGallary);
router.post('/contact',BackEndController.getContact);
router.get('/contact1',BackEndController.getContact1);
router.get('/customer',BackEndController.getCustomerInfo);
router.get('/booking',BackEndController.getBookingInfo);
router.get('/employee',BackEndController.getEmployeeInfo);
router.get('/about',BackEndController.getAbout);
router.get('/booknow',BackEndController.getBook);
router.post('/employee1',BackEndController.createEmployeeInfo1);
router.get('/massage/:id',BackEndController.getMassage);
router.get('/deleteMassage/:id',BackEndController.DeleteMassage);
router.get('/signup',BackEndController.getSignup);
router.post('/signup1',BackEndController.getSignup1);
router.get('/login',BackEndController.getLogin);
router.post('/login1',BackEndController.getLogin1);
router.get('/admin',BackEndController.getAdmin);
module.exports = router;